### ISSUE TITLE
Зачем?

### ISSUE THREAD

**Issue by royalcat** [P4elme6ka/goFileSwamp#1]
![image](https://user-images.githubusercontent.com/13149241/134868720-b1368f03-e248-4ca3-a9a0-9996414354e8.png)

**Comment by P4elme6ka** [comment]
![e9d1ea51c598a3d48f16e43707d9f974](https://user-images.githubusercontent.com/48188631/134871565-c1e83d53-bb6a-4aff-a5d9-0ffa110ef792.jpg)
так нада
